// src/satelliteData.js

// This is our local "database" of satellite information.
// The key for each entry is the satellite's NORAD ID.
// This allows for instant lookups.

export const satelliteInfo = {
  // Featured Satellites
  25544: {
    name: "International Space Station",
    type: 'iss',
    description: "The International Space Station (ISS) is a large space station that was assembled and is maintained in low Earth orbit by a collaboration of five space agencies and their contractors: NASA (United States), Roscosmos (Russia), ESA (Europe), JAXA (Japan), and CSA (Canada). As the largest space station ever constructed, it primarily serves as a platform for conducting scientific experiments in microgravity and studying the space environment. The station is divided into two main sections: the Russian Orbital Segment (ROS), developed by Roscosmos, and the US Orbital Segment (USOS), built by NASA, ESA, JAXA, and CSA. A striking feature of the ISS is the Integrated Truss Structure, which connect the station’s vast system of solar panels and radiators to its pressurized modules. These modules support diverse functions, including scientific research, crew habitation, storage, spacecraft control, and airlock operations. The ISS has eight docking and berthing ports for visiting spacecraft. The station orbits the Earth at an average altitude of 400 kilometres (250 miles) and circles the Earth in roughly 93 minutes, completing 15.5 orbits per day. The ISS programme combines two previously planned crewed Earth-orbiting stations: the United States' Space Station Freedom and the Soviet Union's Mir-2. The first ISS module was launched in 1998, with major components delivered by Proton and Soyuz rockets and the Space Shuttle. Long-term occupancy began on 2 November 2000, with the arrival of the Expedition 1 crew. Since then, the ISS has remained continuously inhabited for 24 years and 288 days, the longest continuous human presence in space. As of August 2025, 290 individuals from 26 countries had visited the station. Future plans for the ISS include the addition of at least one module, Axiom Space's Payload Power Thermal Module. The station is expected to remain operational until the end of 2030, after which it will be de-orbited using a dedicated NASA spacecraft.",
    imageUrl: '/Sat-Images/ISSimage.jpg',
  },
  20580: {
    name: "Hubble Space Telescope",
    type: 'hubble',
    description: "The Hubble Space Telescope (HST) is one of the most important astronomical observatories ever built, launched on April 24, 1990, aboard the Space Shuttle Discovery. It orbits Earth at about 540 km altitude, above the distortion of the atmosphere, giving it a clear and unobstructed view of the universe. Unlike ground-based telescopes, Hubble can capture extremely sharp images across visible, ultraviolet, and near-infrared light, making it a cornerstone of modern space science. The primary mission of Hubble is to explore the origins, structure, and evolution of the universe. It has made groundbreaking discoveries, including measuring the expansion rate of the universe, observing distant galaxies formed soon after the Big Bang, studying black holes at galactic centers, and providing detailed images of planets, stars, and nebulae. Its observations have revolutionized our understanding of dark matter, dark energy, and galaxy formation. Hubble’s mission is ongoing, and despite initial issues with its primary mirror (corrected by astronauts in 1993), it has operated successfully for over three decades. It works in partnership with other major space observatories, like the James Webb Space Telescope (JWST), to provide complementary views of the cosmos. Hubble remains not only a scientific instrument but also a cultural icon, inspiring humanity with stunning images of the universe and fueling curiosity about our place in it.",
    imageUrl: '/Sat-Images/Hubble.jpeg',
  },
  48274: {
    name: "Tiangong Space Station",
    description: "Tiangong (Chinese: 天宫; pinyin: Tiāngōng; lit. 'Heavenly Palace'), officially the Tiangong space station (Chinese: 天宫空间站; pinyin: Tiāngōng kōngjiānzhàn), is a permanently crewed space station constructed by China and operated by China Manned Space Agency. Tiangong is a modular design, with modules docked together while in low Earth orbit, between 340 and 450 km (210 and 280 mi) above the surface. It is China's first long-term space station, part of the Tiangong program and the core of the 'Third Step' of the China Manned Space Program; it has a pressurised volume of 340 m3 (12,000 cu ft), slightly over one third the size of the International Space Station. The space station aims to provide opportunities for space-based experiments and a platform for building capacity for scientific and technological innovation. The construction of the station is based on the experience gained from its precursors, Tiangong-1 and Tiangong-2. The first module, the Tianhe ('Harmony of the Heavens') core module, was launched on 29 April 2021. This was followed by multiple crewed and uncrewed missions and the addition of two laboratory cabin modules. The first, Wentian ('Quest for the Heavens'), launched on 24 July 2022; the second, Mengtian ('Dreaming of the Heavens'), launched on 31 October 2022.",
    imageUrl: '/Sat-Images/Tiangong Space Station.jpg',
  },

  41334: {
    name: "GPS BIIF-12 (USA 265)",
    description: "The GPS IIF-12, also called USA-266 or NAVSTAR 76, is the twelfth and final satellite in the Block IIF series of the Global Positioning System (GPS). Built by Boeing and launched on 5 February 2016 aboard an Atlas V rocket, it marked the completion of the IIF generation, which provided more advanced features than earlier GPS satellites. These upgrades included greater signal accuracy, longer design life, and new civilian and military navigation signals. GPS IIF-12 orbits the Earth in Medium Earth Orbit (MEO) at about 20,400 km altitude, taking roughly 12 hours to complete one orbit. It plays an important role in the global GPS constellation, broadcasting signals that help billions of devices worldwide determine their location, whether for smartphones, airplanes, ships, or military systems. As the capstone of the IIF generation, GPS IIF-12 ensures continuity of service while newer generations like GPS Block III are being deployed. Its mission highlights the U.S. commitment to providing reliable global navigation, timing, and positioning services that have become essential to modern life.",
    imageUrl: '/Sat-Images/GPS IIF-12 (USA-266  NAVSTAR 76).jpg',
  },

  27868: {
    name: "COSMOS 2400",
    description: "The Hubble Space Telescope (HST) is one of the most important astronomical observatories ever built, launched on April 24, 1990, aboard the Space Shuttle Discovery. It orbits Earth at about 540 km altitude, above the distortion of the atmosphere, giving it a clear and unobstructed view of the universe. Unlike ground-based telescopes, Hubble can capture extremely sharp images across visible, ultraviolet, and near-infrared light, making it a cornerstone of modern space science. The primary mission of Hubble is to explore the origins, structure, and evolution of the universe. It has made groundbreaking discoveries, including measuring the expansion rate of the universe, observing distant galaxies formed soon after the Big Bang, studying black holes at galactic centers, and providing detailed images of planets, stars, and nebulae. Its observations have revolutionized our understanding of dark matter, dark energy, and galaxy formation. Hubble’s mission is ongoing, and despite initial issues with its primary mirror (corrected by astronauts in 1993), it has operated successfully for over three decades. It works in partnership with other major space observatories, like the James Webb Space Telescope (JWST), to provide complementary views of the cosmos. Hubble remains not only a scientific instrument but also a cultural icon, inspiring humanity with stunning images of the universe and fueling curiosity about our place in i ",
    imageUrl: '/Sat-Images/COSMOS 2400.jpg'
  }
};